import Layout from "@/components/Layouts/Layout";
import { CareerPage } from "@/modules/career";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function career() {
  return (
    <>
      <Head>
        <title>Gamified learning for top performing students | career</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <CareerPage />
      </Layout>
    </>
  );
}
